account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("tutor-registration/",  views.tutor_registration, name="tutor-registration"),
    path("learner-sign-up/", views.learner_sign_up, name="learner-sign-up"),
    path("login/", views.login_page, name="login"),
    path("terms-condition/", views.terms_condition, name="terms-condition"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("account/", include("account.urls")),
    path("learner/", include("learner.urls")),
    path("tutor/", include("tutor.urls")),
    path("administrator/", include("admin_page.urls")),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
]

home/views.py
from django.shortcuts import render

# Create your views here.
#

def index(request):
    return render(request, "home/index.html")

home/templates/home/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block head %}
  <title>TutorConnect</title>
{% endblock head %}

{% block content %}
<!DOCTYPE html>


    <div class="bg-image">
        <div class="overlay"></div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
            <div class="container">
                <a class="navbar-brand" href="#"><h4>TutorConnect</h4></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'account:login' %}">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#signUpModal">Sign up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container d-flex h-100 align-items-center content">
            <div class="row w-100">
                <div class="col-md-6 find-tutor animated">
                    <h1>FIND YOUR TUTOR</h1>
                    <p>Embark on a learning journey like never before with TutorConnect. Our platform is your gateway to a world of knowledge, offering a diverse range of tutors ready to empower you.</p>
                    <a href="{% url 'account:learner-sign-up' %}" class="btn btn-custom">BE A LEARNER</a>
                </div>
                <div class="col-md-6 text-end become-tutor animated">
                    <h1>BECOME A TUTOR</h1>
                    <p>Step into the role of a tutor and guide learners on TutorConnect, where your expertise transforms lives. Join our community to share your knowledge and inspire a community eager for learning.</p>
                    <a href="{% url 'account:tutor-registration' %}" class="btn btn-custom">BECOME A TUTOR</a>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <div class="row about-section">
            <div class="col-md-6 about-us-section slide-in">
                <h2>About Us</h2>
                <p>TutorConnect is a collaborative effort by a group of college students dedicated to changing the way tutoring services are accessed in the Philippines. With a vision of enhancing educational support, we aim to provide a platform where learners and tutors can connect.</p>
                <h4>Our Team</h4>
                <p>Our team combines skills in web development, design, and user experience. Together, we bring a mix of technical expertise and understanding of the educational landscape in the Philippines. Our goal is to ensure that TutorConnect offers a practical solution for all your tutoring needs.</p>
            </div>
            <div class="col-md-6 about-me-section slide-in-right">
                <h2>Our Story</h2>
                <p>The idea of TutorConnect was inspired by our adviser, who gave us a hint that sparked our imagination. We took that initial idea and expanded it, driven by our collective desire to make quality education accessible to everyone. As students, we understand the challenges of finding reliable and effective tutoring, and we set out to create a solution that addresses these needs.</p>
                <h4>What We Offer</h4>
                <p>At TutorConnect, we provide a directory of tutors across various subjects and levels. Our platform is not only focused on academic subjects but is also open to areas like dancing, singing, and more. As long as the tutor and learner can meet, TutorConnect is here to facilitate the connection. With features and an intuitive interface, TutorConnect makes the process of finding a tutor nearby simple.</p>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="signUpModal" tabindex="-1" aria-labelledby="signUpModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="signUpModalLabel">Sign Up</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <p class="modal-text">Please Choose your role</p>
                    <a href="{% url 'account:learner-sign-up' %}" class="btn btn-primary-custom btn-lg mb-2">Sign Up as Learner</a>
                    <br>
                    <a href="{% url 'account:tutor-registration' %}" class="btn btn-success-custom btn-lg">Sign Up as Tutor</a>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<script>

</script>