admin_page/urls.py
from django.urls import path
from . import views

app_name = "administrator"
urlpatterns = [
    path("dashboard/", views.admin_dashboard, name="admin-dashboard" ),
    path("account-approval/", views.admin_account_approval, name="admin-account-approval" ),
    path("learners-report/", views.admin_learners_report, name="admin-learners-report"),
    path("tutor-report/", views.admin_tutor_report, name="admin-tutor-report"),
    path("user-review/", views.admin_user_review, name="admin-user-review"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("account/", include("account.urls")),
    path("learner/", include("learner.urls")),
    path("tutor/", include("tutor.urls")),
    path("administrator/", include("admin_page.urls")),
]

learner/urls.py
from django.urls import path
from . import views

app_name = "learner"

urlpatterns = [
    path("", views.learner_homepage, name="learner-homepage"),
    path("settings/", views.learner_settings, name="learner-account-settings"),
    path("session-history/", views.learner_session_history, name="learner-session-history"),
    path("tutor-profile/", views.learner_tutor_profile, name="learner-tutor-profile"),
]

core/templates/core/admin-header.html
{% load static %}

 <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
      <div class="d-flex align-items-center justify-content-between">
     <a href="{% url 'administrator:admin-dashboard' %}" class="logo d-flex align-items-center">
          <span class="d-none d-lg-block">TutorConnect</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
      </div>
      <!-- End Logo -->
      
      <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
          <li class="nav-item dropdown pe-3">
            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <img src="{% static 'core/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle" />
              <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
            </a>
            <!-- End Profile Image Icon -->
    
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
              <li>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sign Out</span>
                </a>
              </li>
            </ul>
            <!-- End Profile Dropdown Items -->
          </li>
          <!-- End Profile Nav -->
        </ul>
      </nav>
      <!-- End Icons Navigation -->
    </header>
    <!-- End Header -->

core/templates/core/admin-sidebar.html
{% load static %}
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
      <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
      <a class="nav-link" href="{% url 'administrator:admin-dashboard' %}">
            <i class="bi bi-grid"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <!-- End Dashboard Nav -->

        <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'administrator:admin-learners-report' %}">
            <i class="bi bi-people"></i>
            <span>Learners Report</span>
          </a>
        </li>
        <!-- End Learners Report Nav -->

        <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'administrator:admin-tutor-report' %}">
            <i class="bi bi-person-badge"></i>
            <span>Tutor Report</span>
          </a>
        </li>
        <!-- End Tutor Report Nav -->

        <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'administrator:admin-account-approval' %}">
            <i class="bi bi-check-circle"></i>
            <span>Account Approval</span>
          </a>
        </li>
        <!-- End Account Approval Nav -->

        <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'administrator:admin-user-review' %}">
            <i class="bi bi-star-half"></i>
            <span>User Review</span>
          </a>
        </li>
        <!-- End User Review Nav -->
      </ul>
    </aside>
    <!-- End Sidebar -->

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'core/img/favicon.ico' %}">
    
    {% block head %}
    {% endblock head %}
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/simple-datatables/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet">

    {% block css %}
    {% endblock css %}
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>

     <!-- Vendor JS Files -->
    <script src="{% static 'core/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'core/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'core/vendor/quill/quill.js' %}"></script>
    <script src="{% static 'core/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'core/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'core/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'core/js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>   <!-- Vendor JS Files -->

    <script src="{% static 'core/js/main.js' %}"></script>
    
    {% block script %}
    {% endblock script %}
   
</html>

core/templates/core/header.html
{% load static %}
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'learner:learner-homepage' %}" class="logo d-flex align-items-center">
        <span class="d-none d-lg-block">TutorConnect</span>
      </a>
    </div><!-- End Logo -->
  
    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->
  
    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
            <a class="nav-link nav-icon search-bar-toggle " href="#">
              <i class="bi bi-search"></i>
            </a>
        </li><!-- End Search Icon-->
  
        <!-- Donate Button -->
        <li class="nav-item">
          <a class="nav-link" href="#">
            <button class="btn btn-outline-primary">Donate</button>
          </a>
        </li><!-- End Donate Button -->
  
        <li class="nav-item dropdown">
  
          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-bell"></i>
            <span class="badge bg-primary badge-number">4</span>
          </a><!-- End Notification Icon -->
  
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
            <li class="dropdown-header">
              You have 4 new notifications
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li class="notification-item">
              <i class="bi bi-exclamation-circle text-warning"></i>
              <div>
                <h4>Lorem Ipsum</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>30 min. ago</p>
              </div>
            </li>
  
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li class="notification-item">
              <i class="bi bi-x-circle text-danger"></i>
              <div>
                <h4>Atque rerum nesciunt</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>1 hr. ago</p>
              </div>
            </li>
  
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li class="notification-item">
              <i class="bi bi-check-circle text-success"></i>
              <div>
                <h4>Sit rerum fuga</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>2 hrs. ago</p>
              </div>
            </li>
  
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li class="notification-item">
              <i class="bi bi-info-circle text-primary"></i>
              <div>
                <h4>Dicta reprehenderit</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>4 hrs. ago</p>
              </div>
            </li>
  
            <li>
              <hr class="dropdown-divider">
            </li>
            <li class="dropdown-footer">
              <a href="#">Show all notifications</a>
            </li>
  
          </ul><!-- End Notification Dropdown Items -->
  
        </li><!-- End Notification Nav -->
  
        <li class="nav-item dropdown">
  
          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
          </a><!-- End Messages Icon -->
  
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
              You have 3 new messages
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li class="message-item">
              <a href="#">
                <img src="{% static 'core/img/messages-1.jpg' %}" alt="" class="rounded-circle">
                <div>
                  <h4>Maria Hudson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>4 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li class="message-item">
              <a href="#">
                <img src="{% static 'core/img/messages-2.jpg' %}" alt="" class="rounded-circle">
                <div>
                  <h4>Anna Nelson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>6 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li class="message-item">
              <a href="#">
                <img src="{% static 'core/img/messages-3.jpg' %}" alt="" class="rounded-circle">
                <div>
                  <h4>David Muldon</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>8 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li class="dropdown-footer">
              <a href="#">Show all messages</a>
            </li>
  
          </ul><!-- End Messages Dropdown Items -->
  
        </li><!-- End Messages Nav -->
  
        <li class="nav-item dropdown pe-3">
  
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static 'core/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">Kyle Pagayon</span>
          </a><!-- End Profile Iamge Icon -->
  
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Kevin Anderson</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li>
              <a class="dropdown-item d-flex align-items-center" href="learner-session-history.html">
                <i class="bi bi-grid"></i>
                <span>Session and History</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li>
              <a class="dropdown-item d-flex align-items-center" href="learner-account-setting.html">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>
  
          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->
  
      </ul>
    </nav><!-- End Icons Navigation -->
  
  </header>
  
  <!-- End Header -->

core/templates/core/sidebar.html
{% load static %}
<aside id="sidebar" class="sidebar">
      <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
          <a class="nav-link" href="tutor-dashboard.html">
            <i class="bi bi-grid"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <!-- End Dashboard Nav -->
        <li class="nav-item">
          <a class="nav-link collapsed" data-bs-target="#profile-nav" data-bs-toggle="collapse" href="#">
            <i class="bi bi-menu-button-wide"></i><span>Tutor Profile</span><i class="bi bi-chevron-down ms-auto"></i>
          </a>
          <ul id="profile-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
            <li>
              <a href="profile-personal-information.html">
                <i class="bi bi-circle"></i><span>Personal Information</span>
              </a>
            </li>
            <li>
              <a href="profile-specialties.html">
                <i class="bi bi-circle"></i><span>Specialties</span>
              </a>
            </li>
            <li>
              <a href="profile-education.html">
                <i class="bi bi-circle"></i><span>Education</span>
              </a>
            </li>
            <li>
              <a href="profile-experience.html">
                <i class="bi bi-circle"></i><span>Experience</span>
              </a>
            </li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link collapsed" href="tutor-rating-review.html">
            <i class="bi bi-star-half"></i>
            <span>Rating and Review</span>
          </a>
        </li>
        <!-- End Rating and Review Nav -->

        <li class="nav-item">
          <a class="nav-link collapsed" href="tutor-list-learners.html">
            <i class="bi bi-people"></i>
            <span>Learners</span>
          </a>
        </li>
        <!-- End Learners Nav -->
      </ul>
    </aside>